apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: All production applications
  sourceRepos:
    - https://github.com/Filipcsupka/infra
    - https://bitnami-labs.github.io/sealed-secrets
    - https://charts.min.io/
    - https://grafana.github.io/helm-charts
    - https://nvidia.github.io/dcgm-exporter/helm-charts
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: cv
      server: https://kubernetes.default.svc
    - namespace: vevsdesign
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: ai-chat
      server: https://kubernetes.default.svc
    - namespace: ai-agent
      server: https://kubernetes.default.svc
    - namespace: chaos
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
