apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/filipcsupka/k8s-ai-agent
    newName: ghcr.io/filipcsupka/k8s-ai-agent
    newTag: sha-0e1c563
