apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/filipcsupka/k8s-ai-agent
    newName: ghcr.io/filipcsupka/k8s-ai-agent
    newTag: sha-9b6bbde
  - name: ghcr.io/filipcsupka/k8s-ai-agent-discord-bot
    newName: ghcr.io/filipcsupka/k8s-ai-agent-discord-bot
    newTag: sha-0e1c563
