[control_plane]
family-webapp ansible_host=178.104.235.97 ansible_user=root ansible_ssh_private_key_file=~/.ssh/hetzner_ed25519 tailscale_ip=100.82.16.35 public_ip=178.104.235.97

[gpu_workers]
k3sgpu ansible_host=100.86.152.16 ansible_user=ja ansible_ssh_private_key_file=~/.ssh/hetzner_ed25519 tailscale_ip=100.86.152.16

[hetzner_workers]
k8s-worker-01 ansible_host=178.104.193.227 ansible_user=root ansible_ssh_private_key_file=~/.ssh/hetzner_ed25519 public_ip=178.104.193.227 tailscale_ip=100.119.77.23
