---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: invest-buddy-flex-secrets
  namespace: invest
spec:
  encryptedData:
    FLEX_QUERY_ID: AgC1f1zhATjTwJMyjHTxBhK5JJuyQxbXE3DWwIGp8YwuQVQKj3Ats56r3JCH5QRrF6M1x14XmCvjFDWocKAFwyz2usoyHdW1R0MjnM44VCz1pZYV7GTNYWWaUPtDzAWEHSO0egA4q9yVRJn4CFN0OFvyHiAc1f97ZVrlX/6T4uINhuf0oAf185ihdYk8VvPv82Ta7GARhWW22b1J0Wa3UNC18nU8tfohRruJhZVnHwUTPAczNqqHKNGGOePxMPKjDqz6FZ7/+asg//Y5Ge9EqrS3S1aRIeaKkmRp+DbiZxWFiBKL4oQI81vZtp7hAP6e0DMXT8RwHODhP+1EZmxPfNvfr2vegcpETjXBQYNUrhhsd0I8SbhWQGN5dPaH6dbg9j+Ilt/fS/LAQBTri69JqBuqLmNdi04EdoivBud8AGSwovYwvr97kI+5kn0FXb2L6Y5mK04OaLkbWK5rdwmpRcihXCUTJ99LEMiGVowGgjqOfobWl9tHjAe+3aadpe21sUW4n5mwbWGjvSnPtH5/j6bL2fd8CnTCwvl4H+0Htu8+q93NBcB58sVWyAhybtHx7/jl50ZbwhZNlR04rN1WGQVDbstJhBhIuGI4E1/NqNa9b/VuH4QJRVji6QyCNVhiifqB6vNXH0ThjkXzu+fFl6xPY5joZPuIGlWUxfLzFGMYCwsWnxZ5dHub+kwVFebQIJ0wHjvbUWad
    FLEX_TOKEN: AgCbMrk8bWmVSf3gkZEwgmnKKZVXL9FltoCaSOuOiFPyuvLQr23oRJ0wy339vGFUP8KrtlpsOPVhg2ByNi5+YDyF7FCLlu24Gf8npUdJ3YtWx3csy4vWF3TLyOTzIOpzu8dlSlH0LiHL9+FXC8WdFqQ3jyvngS+JCmEqTgSbUi/X04qNWvNmut0Pw0Q5xb7rlRGdv8r8MAJdHv/IZMybSuHQ2NMh0kAMCaWQKZcG8mY3faWLq7uSQzRScnO961GfX3qwDe6lCLvjct/rHXiESsb863301qPX1cLXCxsm0bbX2fMfcPJ6Uhsbv0lRE405530xzXKtCjPdfQ2qAwt6z84HS3S0WfiX1NKcVcsIs97shWTBSv7r4d1xVdLfxONO8gU+EogdSMjkn5g+XnNrD5XAnm6zTJCwM29+XYuLg2cpcaoPNzlH/im0eESd7VTRxumTP/WEVjgrBrmjzwoVaN2wluGKzVmff3huY/YEWp7qDFoxl4xfDGWFOr3AE1cmZT76QOWQ6kZwc9cOax6Q68iEPRSF1obQRLp2i/as+uqU4LuX4HwZxn68+zp3vp0GD12zVa3VYJPEJwiI0UQmJc3NDGe4TiOn89tKkftnRTlx7Q6g9QNoF3bE0MEEEdOy0s9IFmzN5Czgy6i0PZf9Y1SvKbFxl9ZuAzKyt/ojmMGuDDUIl+4l4Z4LKgc6NZwVVuYVdFWzl4Jn4SP4PM1Ey3FDKbztQnVCmWQ=
  template:
    metadata:
      name: invest-buddy-flex-secrets
      namespace: invest
