---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: invest-buddy-telegram
  namespace: invest
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgA8TfZtvFy7FNzJIMSMF7ciAbwM9h9W8gkCCOQbISPVEurKtcx/05uPkB0fG8ghkoGhjzBpFzhO9F/uqj00+ztPD1nOgl2lKPPlSXE2IYMBUx3/EPyaSZk4Lz+K5qseuVQ8qe/aLHn+DiPqWAYvKAVvBSFSUfsvmvBTsdQMKINxdIUFUcmDjoTwvA6+PR9Z7UfbV669RZg+e0Wo13CrfRibdpE34ArIc54107hIsUbY+RmcwHTCM92VEaDYx81UsV/E6NaIFnctf+8n8FMEO1/kgp2Kr/aiA8v53elJx8pYfIJBn8vwB7K1KzlI/ehQrwFFNdVIuAgt5Pss0A85feL4W4waiS2xaDuWoyWmrKGtD22ic2hPvdgh8k0cvnY1WMmLttszxCGKzx0GoJvng0Y36cIyw++QMq4R6qMl21J6FgcmZKDP9oSyO1yss/PctWjG5odw7l20XDi6p4JVK2oN1FHegPka9XZ7ZqLQd4UOkyUNDa8IV9/kIkOZHQ3WXzhQG/SEq5VYTKP+fkJIHRrCF2sgIm1QXHYYktrBENygDM2RXudyZXjqJMA6Q+NwbGQ/s3js85eTS67xHBulXP3oQspuVEtRsFkv9gMepvwE8Sh8LvnhRhmTEtRilAyu2RkDhVxcTkva8wtP9g8NhiyRaQY35JowIIEh3tR0goBni+45LkxFTFR847wpTtzwnPm4QKpIhuylOtiv2+z28kHsU+h6OmjwvKNr2EGeQNgTm7YFPbyXjNHLMssLc881
    TELEGRAM_CHAT_ID: AgCfY3S/NNHPXEA99Ybxxprl3bhLP4A+bT0P/44SSAal4BwTtLUDDd92fdHzT8lUCiUdIiQKAndQHH0GinqTHXcSfm8SdqzqT614Fk2xhOdJUkBzkTrVnwzxWMTOAsuIGt8ntldX1uByKLpoD+HGdE0r/poADeGw8J1nsjaplfMUuPT15fWoKyjWhvJRLTVgNaec2p4+Ghlt/8NeG47HNEVCkTrzY48WqIo+tKCfCY0wXttv3UlMB6izjSEMsoyo7dpTL5L41BlZaKK6vmQm9rTxhdNAo+Po6C53/akhAKEpOWceSeDffTSu5cnauJA0XXETi57QYERjKzMd/JXi1Dwejy1nK1QmGl6jk5u2aek8nFHf3KBkSeqz5ihYk3wWUwIVXQclRA/T9CK35plRC8mYueBqjZwHVln8b3IB/MPAD0hAGk7TxuB87PNJCfyKl1gHl5fZ3pKRgKi6YxWtb9jHucCyDF0IPBKDoj3hioka/bzx53vQAH/ZQJDHJ93wkNTY4rI3BgZ9oEaaUyR/EDrP1iI+RfcdgQBFt9a6sQtpjENhs5rR7AU1pOQKMrujUeVUkadUQxNtSunx79Oy94tnYFgSsps8zaOYTkExUxw0Rj80q8dA3uHLGo519muafYqEQfnexsXmCWFadL4iZ1LKScJrZg2XdVs/z0CTFNBJ6tKxNDsdauGRGiyncZAoaGhvSgkT/j5ka3eaOAUsww==
  template:
    metadata:
      name: invest-buddy-telegram
      namespace: invest
