---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: invest-buddy-scanner-secrets
  namespace: invest
spec:
  encryptedData:
    CLAUDE_CODE_OAUTH_TOKEN: AgBaxBhttqXrUDEpzlvZm2F+kw30fGDxwLKMRa3Exfp7mQpoAWe8xSOCA6UWDuSz5Ge5RxY64zP+7YjgYP3onO1OrtiHWwMw1Hb4U1PE0uUbFCufLoRaGS4VNR10qhBHow/daHKh6h5F+vmCrS+g1utz/9j1kD0gXF4LdUujOAHb/DSZpErZwueoT+DUEMK/INIQFQi+GRsMy9fra5bsFqTrhJPRk7knC/J5qDfIt20x/LCKUCaZQXmnag2gLqV+naBnj4A/bvD9nRC0CfYBbf5a8v+lrW73YVwBLwD/gJOwgW0gVN+u/f2qdl7w5E09I/UeASuU7Ij2XqowI/DzFS4qTQQiEJvo2wm4rw/itrqPb6CxMJXehII+wWg5a7Q0rdzRYYT8AdKP/bqko8RFIVuMN/pz+BYZkrKD1kb7ffFy5oHyKUeey8gGz8ZAthFYgH67KOOjdgFkioqz/UbogGdDsiBiVryPAbkNRiNaKjw2nrALN3k02DliwahyPuBv+mWBmmFQ4qsA8q6HJDL8gmJu3zCxDn1zz17TcK46jz93gSILAlbqGiVJq34CDQnbtHjbmhg6zIZ7tCIp9oFl5Hf9g27i+39k3TpimnQT52C1ZjIqB+Tn6590DCsWzZ/a31URP0W23+EyT0jaWxIixjwaLCWPKnOFbwZdC13JKmZfDEesvQduBO4D6ZI3wI7G3Qo/BuXpYeiRbNbsAvQIB82w078Wy+AL/5S16T9joqWmlm25l2T0DiZRtR/oBmu0Bc4tdAimYUkUA70Wkhnh/YpmFMscSL23JGI9MEMB02YT4yFSJ+m7Vlm2h3KDrzp9DN71STXWKOLz9uG/QWM=
  template:
    metadata:
      name: invest-buddy-scanner-secrets
      namespace: invest
