---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: invest-buddy-market-secrets
  namespace: invest
spec:
  encryptedData:
    TWELVE_DATA_API_KEY: AgBcig0eJGnJnSY8Ryx5cM00oGM/LgdgKg9Z6XnwXmh0UHcwSYEptgNHeQL4OyY63ckn2uim3fqC/r/BGBKcOv9nH+aXFM6j/oX6aGZto/K05/a47Sx+A1pPHm2cOu2hEij/FOh1m1/Vz93Aq26AvpMUg7H7ZUQTlk9mtBVF2eV7w3UDpcyaPW5cYxiyDT000Rp55k/ncwxa0qtdx9s5jyUcrjH6hb8IaRevEyFC6ppo2eOEg2scfJwZ3iqxiNWgoJ0EqZv8Y71bDTwsB5bobr/X2MWhvAhHudOcu/+mnA/61bZcGGYLHoi8cO4ZO5K5V+xUwo/uaM0+udTndPKYatQ1xsO90GUcpOWppavlyFfPwJ4onW5DwFUdkhjBrtflBko2adx5Ypl2uDpz54KrwGOjVRux5a2yVB9IXt9B6Gwsmg+JBoKdtpDDuFJqDRV+hW+tqLBpIVFKjDZaGVdPWLlHXpTcjYcmRx9+vVHZXU1MOwS494I6htz1T9sCmUXtTZCS/nt80VYC3avyxrGRXU+dp5w2Wi2000dwGPDQAavQQKnecmdNKyetWyXcIlcJBy9vhj785l3+QtivyXSsdxmdVFkpUKkaY4/l1ktw569gti6A7yGpYCztfCfWQRH8Qjs1OrP4//XEjkQG0+k/nNuKA1wneBwcwUBuQDf2km0FmVntokVIZJMRc62rK2DaBFMerssSSWFSHh4key4QyUy+osKDJ0NM8mvDulE/AHtPHw==
  template:
    metadata:
      name: invest-buddy-market-secrets
      namespace: invest
