apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/filipcsupka/memorial-api
  newName: ghcr.io/filipcsupka/memorial-api
  newTag: sha-4bf2046
- name: ghcr.io/filipcsupka/memorial-web
  newName: ghcr.io/filipcsupka/memorial-web
  newTag: sha-6b28305
