apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/filipcsupka/memorial-api
  newName: ghcr.io/filipcsupka/memorial-api
  newTag: sha-81066dc
- name: ghcr.io/filipcsupka/memorial-web
  newName: ghcr.io/filipcsupka/memorial-web
  newTag: sha-5cf3ce0
