apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/filipcsupka/memorial-api
  newName: ghcr.io/filipcsupka/memorial-api
  newTag: sha-087f6c8
- name: ghcr.io/filipcsupka/memorial-web
  newName: ghcr.io/filipcsupka/memorial-web
  newTag: sha-e7892d7
