---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-bot-secrets
  namespace: ai-agent
spec:
  encryptedData:
    bot-token: AgBUsfQaJk4tDnUMM85K6GLO9VRcdApMAnIzAZ32XOZ0tf0BC/mcofdqF/Wml/KujWgFpFlmZq90l5X6PnwiaR5RJJ73NFCEYLkB05lxSYPEDG+AF+YVcJ6LI+QxOMpx6Spnew19NKUSc92HfoL9hi0LPU+6WkGfxWeoKLxz+yPb6ktW9jvzGVAXgFOxQEQ6SZxkHC7mqmDF0yR83vzVHjSS443RD4TgDB2XWBwaKjkkYcQj5QdutPZDsBC0PhghqPEOMZ4LgszhGzOq+r2F69eaqxiuoYR8WgTphJ3abOEReGuxT3ZH32LqWJoSVvxsGoNc0tt4mwwN7XYqt/OYYug1bIogdjGguyLSHsBR+flFEN9ijM4an9Ab8IbJocggavg7Gx7bwQUD3YFk+764GSso8fdKfBPsFaabjfhxovWvHxBrFgAz2u49iMJe2iwDI5ghnGaKNvGxI93CGGPhtLxllMKS8QGWUezpHp7gq9/trUAQH0iJ2GgafRTDcqGOVVn3T5DO6D0eZAVT77BCqOSpQH2UsLmZXoF8l+sKW/3ZsqBrGYX7HQ2N7Uwk0c03qdAf68QZUjD5NflJVRLYr0BLva3s08lYOP1SyW3g8e0qZC441uPExn4oBHBpWKNh/Wugv/Rvm0wKnssJsO+On8uF8IW7dwjQAm5mQ3DgoK0+1p+zA9jpqdTstkDpzkyRppVHpK9JFudynbJJKSaiN7MiCG4LzU81wAPMgNow60FbEBzsaEWBf6chnCaREFdo1x7Gy0D1BzPix20hVxxCLhmo06P+gaTi0BI=
  template:
    metadata:
      name: discord-bot-secrets
      namespace: ai-agent
