---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k8s-ai-agent-secrets
  namespace: ai-agent
spec:
  encryptedData:
    discord-webhook-url: AgAiAQKmIj3WZwH9+xZnM40s6RsZ0TZKmwQMB4pJmhc/k9ne1I6uEfL31jn55yNw4afGJPwwTHoDtedo4/t5/tY8/o1IqzYveJmnTeUztGZkjttBU+QCTe8MKqSpRKw8HkWEKvFCjB4MxAf4oOEHsZbvJpPQmUxu/aZ88ILC3WHibOJdHm6NJ4gZEbXEKvBMgK5EsEP6GE6VIvf9rn0WLZbmA2VWIisvP+cLF9oNiD1SvmgD2MMsrD37mMY7mjRugMR3sRU4V6qH6mHcOeBoc40gd/7taGsH477TZ7+dNLsIwYDaCOueZBrfN53+deuyza7lR/5i4KTc+ZCeQJmUy9JIQU0valluApj2tfTQiSmMyq1gz0UO87VK2IpQ2UQd6npt0YGsmhLIQn++GNkiQHcM63DbQnU/sezG8ODss5YHDKzhJuCW2yQeZ0gI1iv6jRsjsvL53PPlUqZwjqm93y267Op+MUIL6B8WdsLW09x5Jieq+1EQdZltwbyz4EVgFOhTi3zOF76ka81QFUxuETyPxeQgmYpN9x9/RC/pkKqLUXXFNh3Q4a4R8rHRb66yoiGEGE7zCjmDWKsIp0pFVBu+a8vR05DVmTEHlXnM61ktSk90mm9lQs2NV8mBO9paAo/wsu2FLDlGisragdeiM8F9NerVf2W9gnCFwP+RGnIs6zRJ6bHmHqx66/FPKdnlLrFIZ25BemfDlHulCngNTlCQsHNIvdyV3/G4Sth9VBiLrK8zOo26Td3sFhTiMhsSB+FA6IfKuO4aTIOm1zvazylWKmBTpLU0goawxJHfbO0VlvsQXaTu4ZUwkq/LmwsmFBsJ3k2vkPfeJJmq2Mv+Tdf+0NfdAffryT9Y
  template:
    metadata:
      name: k8s-ai-agent-secrets
      namespace: ai-agent
