apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/filipcsupka/vevsdesign
  newName: ghcr.io/filipcsupka/vevsdesign
  newTag: sha-0ec5c4e
