apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minio.yaml
  - prometheus-crds.yaml
  - prometheus-stack.yaml
  - loki.yaml
  - dcgm-exporter.yaml
  - alloy.yaml
  - monitoring-kuma.yaml
  - sealed-secrets.yaml
