apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-agent-secrets
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/Filipcsupka/infra
    targetRevision: HEAD
    path: gitops/sealed-secrets/ai-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
