apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invest-buddy
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/Filipcsupka/infra
    targetRevision: HEAD
    path: gitops/apps/invest-buddy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: invest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
