apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ai-chat.yaml
  - chaos-generator.yaml
  - k8s-ai-agent.yaml
  - my-cv.yaml
  - vevsdesign.yaml
  - ai-agent-secrets.yaml
