apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/filipcsupka/invest-buddy
  newName: ghcr.io/filipcsupka/invest-buddy
  newTag: sha-e550a4d
- name: ghcr.io/filipcsupka/invest-buddy-scanner
  newName: ghcr.io/filipcsupka/invest-buddy-scanner
  newTag: sha-e550a4d
