apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - alertmanagerconfig.yaml
  - crashloop.yaml
  - oomkilled.yaml
  - imagepull.yaml
  - slow-crash.yaml
  - pending.yaml
  - config-error.yaml
