apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filip-cv
  namespace: cv
spec:
  ingressClassName: traefik
  rules:
    - host: filipcsupka.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filip-cv
                port:
                  number: 80
