apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2        # TODO: rename to actual app name
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/Filipcsupka/infra
    targetRevision: HEAD
    path: gitops/apps/app-2/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: app-2  # TODO: set actual namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
